handissimo_aboutpage:
    path:     /about
    defaults: { _controller: "HandissimoBundle:Default:about" }
    methods:  GET

handissimo_homepage:
    path:     /
    defaults: { _controller: "HandissimoBundle:Default:index" }
    methods:  GET