pictures_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:Pictures:index" }
    methods:  GET

pictures_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:Pictures:show" }
    methods:  GET

pictures_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:Pictures:new" }
    methods:  [GET, POST]

pictures_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:Pictures:edit" }
    methods:  [GET, POST]

pictures_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:Pictures:delete" }
    methods:  DELETE
