research_ajax:
    path:   /ajax/{keyword}
    defaults: {_controller: "HandissimoBundle:Ajax:autoComplete"}
    methods:  POST

city_ajax:
    path:   /ajaxcity/{postalcode}
    defaults: {_controller: "HandissimoBundle:Ajax:postal"}
    methods:  POST

research_action:
    path:     /
    defaults: { _controller: "HandissimoBundle:Ajax:research" }
    methods:  [GET, POST]

search_advanced:
    path:   /advanced/{disabilitytypes}/{structurestypes}/{needs}/{idsearch}
    defaults:   { _controller: "HandissimoBundle:Ajax:researchAdvanced"}
    methods:    [GET, POST]

