research_ajax:
    path:   /ajax/{keyword}
    defaults: {_controller: "HandissimoBundle:Ajax:autoComplete"}
    methods:  POST

city_ajax:
    path:   /ajaxcity/{postalcode}
    defaults: {_controller: "HandissimoBundle:Ajax:postal"}
    methods:  POST

research_action:
    path:     /
    defaults: { _controller: "HandissimoBundle:Ajax:research" }
    methods:  [GET, POST]

advanced_research_action:
    path:     /research/{pagination}/
    defaults: { _controller: "HandissimoBundle:Ajax:advancedResearch" }
    methods:  [GET, POST]



