research_home:
    path:     /new
    defaults: { _controller: "HandissimoBundle:Ajax:research" }
    methods:  [GET, POST]

research_index:
    path:     /ajax/{keyword}
    defaults: { _controller: "HandissimoBundle:Ajax:autoComplete" }
    methods:  POST

city_ajax:
    path:   /ajaxcity/{postalcode}
    defaults: { _controller: "HandissimoBundle:Ajax:postal"}
    methods: POST