handissimo:
    resource: "@HandissimoBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

opinion:
    resource: "@HandissimoBundle/Controller/"
    type:     annotation
    prefix:   /ajax