# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.organizations:
        class: HandissimoBundle\Admin\OrganizationsAdmin
        arguments: [~, HandissimoBundle\Entity\Organizations, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "dossier", label: "Structure" }

    admin.society:
            class: HandissimoBundle\Admin\SocietyAdmin
            arguments: [~, HandissimoBundle\Entity\Society, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: "dossier", label: "Société" }

    admin.structures_types:
            class: HandissimoBundle\Admin\StructuresTypesAdmin
            arguments: [~, HandissimoBundle\Entity\StructuresTypes, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: "dossier", label: "Type de structure" }


