handissimo_opinion:
    resource: "@HandissimoBundle/Resources/config/routing/opinion.yml"
    prefix:   /opinion

handissimo_homepage:
    path:     /
    defaults: { _controller: HandissimoBundle:Default:index }
