services:
#    handissimo.example:
#        class: HandissimoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


parameters:

    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
