HandissimoBundle\Entity\Opinion:
    properties:
        eMail:
            - Email:
                message: L'email "{{ value }}" n'est pas valide.
                checkMX: true
                strict: true