HandissimoBundle\Entity\DisabilityTypes:
    type: entity
    table: disability_types
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        disabilityName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: disability_name
    manyToMany:
        organizations:
            targetEntity: Organizations
            mappedBy: disabilityTypes

    lifecycleCallbacks: {  }
