HandissimoBundle\Entity\Needs:
    type: entity
    table: needs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        needName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: need_name
    manyToMany:
        organizations:
            targetEntity: Organizations
            mappedBy: needs


    lifecycleCallbacks: {  }
