HandissimoBundle\Entity\Organizations:
    type: entity
    table: organizations
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 255
        adress:
            type: string
            nullable: false
            length: 255
        postal:
            type: string
            nullable: false
            length: 255
        city:
            type: string
            nullable: false
            length: 255
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
        phoneNumber:
            type: string
            nullable: false
            length: 255
        mail:
            type: string
            nullable: false
            length: 255
        website:
            type: string
            nullable: true
            length: 255
        blog:
            type: string
            nullable: true
            length: 255
        facebook:
            type: string
            nullable: true
            length: 255
        twitter:
            type: string
            nullable: true
            length: 255
        agegroup:
            type: string
            nullable: true
            length: 255
        freeplace:
            type: string
            nullable: true
            length: 255
        organizationDescription:
            type: text
            nullable: false
            length: 65535
        serveDescription:
            type: text
            nullable: true
            length: 65535
        openhours:
            type: string
            nullable: true
            length: 255
        opendays:
            type: string
            nullable: true
            length: 255
        teamMembersNumber:
            type: integer
            nullable: true
        teamDescription:
            type: text
            nullable: true
            length: 65535
        updateDatetime:
            type: datetime
            nullable: true
        workingDescription:
            type: text
            nullable: true
            length: 65535
        school:
            type: boolean
            nullable: true
        schoolDescription:
            type: text
            nullable: true
            length: 65535
        activities:
            type: text
            nullable: true
            length: 65535
        placeDescription:
            type: text
            nullable: true
            length: 65535
        doc:
            type: string
            nullable: true
            length: 255
        profilPicture:
            type: string
            nullable: true
            length: 255
    manyToOne:
        structuretype:
            targetEntity: StructuresTypes
            inversedBy: organizationtype
            joinColumn:
                name: structurestypes_id
                referencedColumnName: id

        picture:
            targetEntity: Pictures
            inversedBy: organizationpicture
            joinColumn:
                name: pictures_id
                referencedColumnName: id
            orphanRemoval: false

        societies:
            targetEntity: Society
            inversedBy: organization
            joinColumn:
                name: societies_id
                referencedColumnName: id
    manyToMany:
        disabilityTypes:
            targetEntity: DisabilityTypes
            inversedBy: organizations
            joinTable:
                name: disability_types_has_organizations
                joinColumns:
                    organizations_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    disability_types_id:
                        referencedColumnName: id
        needs:
            targetEntity: Needs
            inversedBy: organizations
            joinTable:
                name: needs_has_organizations
                joinColumns:
                    organizations_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    needs_id:
                        referencedColumnName: id

        stafforganizations:
            targetEntity: Staff
            inversedBy: organizations
            joinTable:
                name: organizations_has_staff
                joinColumns:
                    organizations_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    staff_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
