HandissimoBundle\Entity\Society:
    type: entity
    table: society
    indexes:
        fk_managers_structures1_idx:
            columns:
                - structures_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        societyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: society_name
        logo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        postal:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phoneNumber:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: phone_number
        mail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        societyTwitter:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: society_twitter
        societyFacebook:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: society_facebook
        website:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    oneToOne:
        structures:
            targetEntity: Organizations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                structures_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
