HandissimoBundle\Entity\StaffTypes:
    type: entity
    table: staff_types
    indexes:
        fk_Staff_types_staff1_idx:
            columns:
                - staff_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        secteur:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        stafftypes:
            targetEntity: Staff
            mappedBy: staff

    lifecycleCallbacks: {  }
