HandissimoBundle\Entity\Staff:
    type: entity
    table: staff
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        jobs:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        others:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false

    manyToOne:
        staff:
            targetEntity: StaffTypes
            inversedBy: typesstaff
            joinColumn:
                name: stafftypes_id
                referencedColumnName: id

    manyToMany:
        organizations:
            targetEntity: Organizations
            mappedBy: stafforganizations

    lifecycleCallbacks: {  }
