HandissimoBundle\Entity\StructuresTypes:
    type: entity
    table: structures_types
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        structuresType:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: Structures_type
        logoMdph:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: logo_mdph
    oneToMany:
        organizationtype:
            targetEntity: Organizations
            mappedBy: structuretype

    lifecycleCallbacks: {  }
