# src/HandissimoBundle/Resources/config/doctrine/User.orm.yml
HandissimoBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        facebook_id:
          type: string
          length: 255
          nullable: true
        google_id:
            type: string
            length: 255
            nullable: true